services:
  asteroids:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mynet
    image: mariamcparland/asteroids

networks:
  mynet:
